<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SimpleExec" Version="13.1.0" />
    <PackageReference Include="TUnit" Version="1.66.27" />
  </ItemGroup>

</Project>
