name: Publish

on:
  release:
    types:
      - published

env:
  DOTNET_NOLOGO: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            10.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.x'

      - name: Calculate version
        uses: gittools/actions/gitversion/execute@v4.7.0

      - name: Deploy
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./build.sh publish
